apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-hello-world_deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-web-hello-world
  template:
    metadata:
      labels:
        app: go-web-hello-world
    spec:
      containers:
      - name: my-demo
        image: lyt2000/go-web-hello-world:v0.1
        ports:
        - containerPort: 31080
